# Getting ready to test the workflow run on workflow dispatch with input selection event

name: Terraform CD
on:
  workflow_dispatch:
    inputs:
      env_select:
        description: "Select the environment to configure: "
        required: true
        default: "dev_env"
        type: choice
        options:
          - dev_env
          - uat_env

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Check environment
        run: echo "Selected environment is ${{ github.event.inputs.env_select }}"

      - name: Checkout Codes
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var-file="./Environments/${{ github.event.inputs.env_select }}.tfvars" -out="terraform_out"
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve "terraform_out"
